const DATA = {
"Parâmetros de Sistema": [
{"id":"2C026009","name":"Idioma               :","value":       0,"min":       0,"max":       2,"def":       0,"unit":"  ","help":"0=Português 1=Inglês 2=Espanhol"},
{"id":"2C038005","name":"Modo Operação        :","value":       1,"min":       0,"max":       2,"def":       0,"unit":"  ","help":"0=Normal 1=Debug 2=Aferição equipamento"},
{"id":"2402A002","name":"Instante Pesagem     :","value":    2000,"min":       0,"max":    5000,"def":    2000,"unit":"ms","help":"Tempo para iniciar pesagem após acionamento do sensor."},
{"id":"2C04A009","name":"Unidade              :","value":       0,"min":       0,"max":       3,"def":       0,"unit":"  ","help":"Escolhe unidade 0=g 1=kg 2=lb 3=oz"},
{"id":"2C046009","name":"Separador            :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"0=Vírgula (,) 1=Ponto (.)"},
{"id":"2C012009","name":"Casas Decimais       :","value":       0,"min":       0,"max":       3,"def":       0,"unit":"  ","help":"3=x.xxx 2=xx.xx 1=xx.x 0=xxxx"},
{"id":"3C006009","name":"Usa PLC LK100        :","value":       0,"min":       0,"max":       2,"def":       0,"unit":"  ","help":"0:Desativar 1:Ativar 2:PLC Aplicador (restart)"},
{"id":"3D652009","name":"Saídas Pulsadas PLC  :","value":       8,"min":       0,"max":      24,"def":       2,"unit":"  ","help":"2 para aplicador; número saídas pulsadas"},
{"id":"3D650009","name":"Saídas Contínuas PLC :","value":       8,"min":       0,"max":      24,"def":       2,"unit":"  ","help":"2 para aplicador; número de saídas contínuas"},
{"id":"32038009","name":"Modo OP              :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"Origem da OP: 1=Vis"},
{"id":"25236002","name":"Menor Peso Faixa M   :","value":    1000,"min":       0,"max":  500000,"def":       0,"unit":"g ","help":"Peso mínimo da faixa média"},
{"id":"25232002","name":"Maior Peso Faixa M   :","value":    2000,"min":       0,"max":  500000,"def":       0,"unit":"g ","help":"Peso máximo da faixa média"}
],
"Parâmetros de Produção": [
{"id":"0E006000","name":"Data de Produção      :","value":       1,"min":       0,"max":       1,"def":       1,"unit":"  ","help":"1=Habilita / 0=Desabilita"},
{"id":"12006000","name":"Lote                 :","value":       0,"min":       0,"max":       1,"def":       1,"unit":"  ","help":"1=Habilita / 0=Desabilita"},
{"id":"34006002","name":"Turno                :","value":       0,"min":       0,"max":       1,"def":       1,"unit":"  ","help":"1=Habilita / 0=Desabilita"},
{"id":"3000600A","name":"Subturno             :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"1=Habilita / 0=Desabilita"},
{"id":"38006008","name":"Martelo              :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"1=Habilita / 0=Desabilita"},
{"id":"10006004","name":"Data de Rendimento    :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"Cálculo de rendimento 1=Habilita / 0=Desabilita"},
{"id":"32006006","name":"Ordem de Produção     :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"1=Habilita / 0=Desabilita"},
{"id":"3A006000","name":"Produto              :","value":       1,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"1=Digitar cód. produto; 0=Auto-detectar barcode"},
{"id":"0E036006","name":"Data Produção Mínima  :","value":       1,"min":       0,"max":     180,"def":       1,"unit":"d ","help":"0=Não / ou informar quantidade de dias."},
{"id":"0E032006","name":"Data Produção Máxima  :","value":       0,"min":       0,"max":       5,"def":       0,"unit":"d ","help":"0=Não / ou informar quantidade de dias."},
{"id":"34032006","name":"Turno Máximo         :","value":       4,"min":       1,"max":       9,"def":       4,"unit":"  ","help":"Define o número máximo de turnos permitidos."},
{"id":"2200600A","name":"Validação            :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"Ativa ou desativa a validação dos parâmetros."},
{"id":"4200600A","name":"Login                :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"Ativa ou desativa Login."}
],
"Parâmetros de Calibração": [
{"id":"24036002","name":"Menor Peso            :","value":     200,"min":       0,"max":   50000,"def":     200,"unit":"g ","help":"Menor peso considerado para uma pesagem válida."},
{"id":"2400C002","name":"Peso Calib Balança   :","value":    1000,"min":    1000,"max":  200000,"def":   10000,"unit":"g ","help":"Peso de calibração deve estar entre 20% e 120% peso máximo."},
{"id":"1C022006","name":"Filtro Amplificador  :","value":       7,"min":       0,"max":      10,"def":       8,"unit":"  ","help":"Filtro aceito 0..10 Padrão: 7"},
{"id":"2404E002","name":"Velocidade Pesagem   :","value":       0,"min":       0,"max":       7,"def":       1,"unit":"  ","help":"Velocidade de Pesagem ."},
{"id":"2403200A","name":"Peso Máximo Balança  :","value":    5000,"min":    5000,"max":  500000,"def":   50000,"unit":"g ","help":"Peso máximo suportado pela balança."},
{"id":"1C038002","name":"Modo do Filtro       :","value":       1,"min":       0,"max":       2,"def":       1,"unit":"  ","help":"0=filtro padrão 1=filtro rápido"},
{"id":"2403C005","name":"Resolução Gramas     :","value":       1,"min":       1,"max":     100,"def":      10,"unit":"  ","help":"Valor padrão: 1 Aceito: 1, 2, 5, 10, 20, 50, 100"}
],
"Parâmetros de Pesagem": [
{"id":"2E006000","name":"Zero Automático       :","value":       1,"min":       0,"max":       2,"def":       1,"unit":"  ","help":"Habilita busca de zero: 0=Não / 1=Sim"},
{"id":"1C044008","name":"Filtro SW            :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"Habilita filtro de software: 0=Não / 1=Sim"},
{"id":"2C03C001","name":"Resolução Gramas     :","value":      10,"min":       1,"max":     100,"def":      10,"unit":"  ","help":"Valor padrão: 1. Aceitos: 1, 2, 5, 10, 20, 50, 100"},
{"id":"24010002","name":"Valor Delta          :","value":      20,"min":       1,"max":     250,"def":      20,"unit":"g ","help":"Descarta pesos fora do limite para realizar a média."},
{"id":"0D31E002","name":"Fator Correção fx P  :","value":   10000,"min":    9000,"max":   11000,"def":   10000,"unit":"  ","help":"Ajuste fino de calibração. Padrão: 10000 = 100.00%"},
{"id":"0D21E002","name":"Fator Correção fx M  :","value":   10000,"min":    9000,"max":   11000,"def":   10000,"unit":"  ","help":"Ajuste fino de calibração. Padrão: 10000 = 100.00%"},
{"id":"0D11E002","name":"Fator Correção fx G  :","value":   10000,"min":    9000,"max":   11000,"def":   10000,"unit":"  ","help":"Ajuste fino de calibração. Padrão: 10000 = 100.00%"},
{"id":"2E010006","name":"Delta Zero           :","value":       5,"min":       1,"max":      50,"def":       5,"unit":"g ","help":"Usado para descartar pesos com variação superior."},
{"id":"2E034006","name":"Qtd Amostras Média Z :","value":      50,"min":      10,"max":     500,"def":      50,"unit":"  ","help":"Número de amostras consideradas para a média."},
{"id":"2E01200A","name":"Passo Envelope       :","value":       5,"min":       1,"max":     100,"def":       5,"unit":"  ","help":"Quantidade de amostras para o passo."},
{"id":"2E016006","name":"Gap de Envelope      :","value":      10,"min":       2,"max":     100,"def":      10,"unit":"g ","help":"Abertura da área de atuação do envelope."}
],
"Parâmetros Classificadora": [
{"id":"3E032002","name":"Peças Máximo Batch   :","value":    5000,"min":      50,"max":    5000,"def":    5000,"unit":"pc","help":"Número de peças para forçar o Batch."},
{"id":"3E034002","name":"Máx. Média Buffer    :","value":    1000,"min":     100,"max":    1000,"def":    1000,"unit":"  ","help":"Número de peças usadas no cálculo do algoritmo inteligente."},
{"id":"0604E00A","name":"Velocidade Esteira   :","value":     500,"min":       1,"max":    2000,"def":     500,"unit":"v ","help":"Em milímetros por segundo."},
{"id":"3E008002","name":"Tempo Espera Fecha B.:","value":    1000,"min":      10,"max":    2000,"def":    1000,"unit":"ms","help":"Tempo para fechar o Batch após a última peça."},
{"id":"3E002002","name":"Buffer ON            :","value":       0,"min":       0,"max":       2,"def":       1,"unit":"  ","help":"1=Habilita Buffer; 2=liga esteira."},
{"id":"4001200A","name":"Número de Braços    :","value":       8,"min":       1,"max":      24,"def":       8,"unit":"  ","help":"Quantidade de braços da classificadora."},
{"id":"40000006","name":"Braços em 2 Linhas  :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"0=uma linha 1=duas linhas."},
{"id":"40108006","name":"Tempo Espera Braço 1 :","value":       0,"min":       0,"max":    5000,"def":       0,"unit":"ms","help":"Tempo de espera para o primeiro braço."},
{"id":"40014006","name":"Tempo Entre Braços   :","value":       0,"min":       0,"max":    5000,"def":       0,"unit":"ms","help":"Tempo de atraso entre braços em ms."},
{"id":"0600800A","name":"Tempo Atraso Esteira :","value":       0,"min":       0,"max":   10000,"def":       0,"unit":"ms","help":"Tempo de atraso da esteira antes de abrir."},
{"id":"0604200A","name":"Direção Esteira      :","value":       0,"min":       0,"max":       1,"def":       0,"unit":"  ","help":"0=mesmo sentido da classificadora 1=sentido contrário."},
{"id":"4403800A","name":"Modo Qualidade       :","value":       0,"min":       0,"max":       4,"def":       0,"unit":"  ","help":"0=off;1=plc sem rejeito;2=plc com rejeito;3=2 sensores;4=1 S"},
{"id":"4404800A","name":"Time out qualidade    :","value":     300,"min":      10,"max":    2000,"def":     300,"unit":"ms","help":"Tempo de espera para receber uma qualidade válida."},
{"id":"4405000A","name":"N. Ganchos Qualidade :","value":     100,"min":       0,"max":    1000,"def":     100,"unit":"  ","help":"Ganchos entre a balança e o sensor de qualidade. "},
{"id":"4400600A","name":"Time In qualidade    :","value":      30,"min":       0,"max":    2000,"def":      30,"unit":"ms","help":"Tempo máximo para procurar uma qualidade válida."}
]
};
